apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: reactive
  name: reactive
spec:
  ports:
  - name: 8082-8080
    port: 8082
    protocol: TCP
    targetPort: 8080
  selector:
    app: reactive
  clusterIP: None
status:
  loadBalancer: {}
