apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rest-mvc
  name: rest-mvc
spec:
  ports:
  - name: 8081-8080
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: rest-mvc
  clusterIP: None
status:
  loadBalancer: {}
