services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_USER: restadmin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: restdb
      MYSQL_ROOT_PASSWORD: password
    expose:
      - "3306"
  mongo-db:
    container_name: mongo-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  auth-server:
    container_name: auth-server
    image: spring-6-auth-server:0.0.1-SNAPSHOT
    ports:
      - "9000:9000"
  rest-mvc:
    container_name: rest-mvc
    image: spring-6-rest-mvc:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server:9000
    depends_on:
      - mysql
      - auth-server
    links:
      - mysql
      - auth-server
    ports:
      - "8081:8080"
  reactive:
    container_name: reactive
    image: spring-6-reactive:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - auth-server
    ports:
      - "8082:8080"
  reactive-mongo:
    container_name: reactive-mongo
    image: reactivemongo:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - auth-server
      - mongo-db
    ports:
      - "8083:8080"
  gateway:
    container_name: gateway
    image: spring-6-cloud-gateway:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    links:
      - auth-server
      - rest-mvc
      - reactive
      - reactive-mongo
